name = input("enter your Full name: ")
age = int(input("enter your age: "))
city = input("enter your city: ")
university = input("enter your university: ")
department = input("enter your department: ")
fav_programing_language = input("enter your favoriet programing language: ")
goal = input("enter your programing goal: ")

print("======================================= STUDENT INTRODUCTION ======================================== ")
print(f"My name is {name}.")
print(f"I am {age} years old.")
print(f"I live in {city}.")
print(f"I study {department} at {university} university.")
print(f"My favorite programming language is {fav_programing_language}.")
print(f"My programming goal: {goal}.")